
env:
   global:
     - CONAN_REFERENCE: "opencv/3.2.0"
     - CONAN_USERNAME: "ulricheck"
     - CONAN_LOGIN_USERNAME: "ulricheck"
     - CONAN_CHANNEL: "stable"
     - CONAN_UPLOAD: "https://api.bintray.com/conan/tum-ubitrack/public-conan"
     - CONAN_STABLE_BRANCH_PATTERN: "release/*"
     - CONAN_UPLOAD_ONLY_WHEN_STABLE: 1 # Will only upload when the branch matches "release/*"

linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.6"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:
      - <<: *osx
        osx_image: xcode8.3
        env: CONAN_APPLE_CLANG_VERSIONS=8.3 CONAN_TOTAL_PAGES=4 CONAN_CURRENT_PAGE=1
      - <<: *osx
        osx_image: xcode8.3
        env: CONAN_APPLE_CLANG_VERSIONS=8.3 CONAN_TOTAL_PAGES=4 CONAN_CURRENT_PAGE=2
      - <<: *osx
        osx_image: xcode8.3
        env: CONAN_APPLE_CLANG_VERSIONS=8.3 CONAN_TOTAL_PAGES=4 CONAN_CURRENT_PAGE=3
      - <<: *osx
        osx_image: xcode8.3
        env: CONAN_APPLE_CLANG_VERSIONS=8.3 CONAN_TOTAL_PAGES=4 CONAN_CURRENT_PAGE=4
      - <<: *linux
        env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49 CONAN_TOTAL_PAGES=4 CONAN_CURRENT_PAGE=1
      - <<: *linux
        env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49 CONAN_TOTAL_PAGES=4 CONAN_CURRENT_PAGE=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49 CONAN_TOTAL_PAGES=4 CONAN_CURRENT_PAGE=3
      - <<: *linux
        env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49 CONAN_TOTAL_PAGES=4 CONAN_CURRENT_PAGE=4
      - <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc54 CONAN_TOTAL_PAGES=4 CONAN_CURRENT_PAGE=1
      - <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc54 CONAN_TOTAL_PAGES=4 CONAN_CURRENT_PAGE=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc54 CONAN_TOTAL_PAGES=4 CONAN_CURRENT_PAGE=3
      - <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc54 CONAN_TOTAL_PAGES=4 CONAN_CURRENT_PAGE=4
      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc63 CONAN_TOTAL_PAGES=4 CONAN_CURRENT_PAGE=1
      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc63 CONAN_TOTAL_PAGES=4 CONAN_CURRENT_PAGE=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc63 CONAN_TOTAL_PAGES=4 CONAN_CURRENT_PAGE=3
      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc63 CONAN_TOTAL_PAGES=4 CONAN_CURRENT_PAGE=4



      - <<: *osx
        osx_image: xcode9
        env: CONAN_APPLE_CLANG_VERSIONS=9.0
      - <<: *linux
        env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49
      - <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc54
      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc63

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
