
env:
   global:
     - CONAN_REFERENCE: "opencv/3.4.12"
     - CONAN_USERNAME: "camposs"
     - CONAN_LOGIN_USERNAME: "camposs"
     - CONAN_CHANNEL: "stable"
     - CONAN_UPLOAD: "https://conan.campar.in.tum.de/api/conan/conan-camposs"
     - CONAN_REMOTES: "https://conan.campar.in.tum.de/api/conan/conan-camposs"
     - CONAN_STABLE_BRANCH_PATTERN: "release/*"
     - CONAN_UPLOAD_ONLY_WHEN_STABLE: 1 # Will only upload when the branch matches "release/*"
     - CONAN_ARCHS: x86_64

linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.6"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:
      - <<: *osx
        osx_image: xcode9
        env: CONAN_APPLE_CLANG_VERSIONS=9.0 CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=1
      - <<: *osx
        osx_image: xcode9
        env: CONAN_APPLE_CLANG_VERSIONS=9.0 CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49 CONAN_TOTAL_PAGES=4 CONAN_CURRENT_PAGE=1
      - <<: *linux
        env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49 CONAN_TOTAL_PAGES=4 CONAN_CURRENT_PAGE=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49 CONAN_TOTAL_PAGES=4 CONAN_CURRENT_PAGE=3
      - <<: *linux
        env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49 CONAN_TOTAL_PAGES=4 CONAN_CURRENT_PAGE=4
      - <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc54 CONAN_TOTAL_PAGES=4 CONAN_CURRENT_PAGE=1
      - <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc54 CONAN_TOTAL_PAGES=4 CONAN_CURRENT_PAGE=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc54 CONAN_TOTAL_PAGES=4 CONAN_CURRENT_PAGE=3
      - <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc54 CONAN_TOTAL_PAGES=4 CONAN_CURRENT_PAGE=4
      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc63 CONAN_TOTAL_PAGES=4 CONAN_CURRENT_PAGE=1
      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc63 CONAN_TOTAL_PAGES=4 CONAN_CURRENT_PAGE=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc63 CONAN_TOTAL_PAGES=4 CONAN_CURRENT_PAGE=3
      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc63 CONAN_TOTAL_PAGES=4 CONAN_CURRENT_PAGE=4

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
